// <auto-generated />
using System;
using ErpDemo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ErpDemo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpDemo.Domain.Entities.Customer", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Document").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("Document").IsUnique();
                b.ToTable("Customers");
            });

            modelBuilder.Entity("ErpDemo.Domain.Entities.Order", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<decimal>("Total").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("CustomerId");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("ErpDemo.Domain.Entities.OrderItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<Guid>("OrderId").HasColumnType("uniqueidentifier");
                b.Property<int>("Quantity").HasColumnType("int");
                b.Property<decimal>("UnitPrice").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("ErpDemo.Domain.Entities.Order", b =>
            {
                b.HasOne("ErpDemo.Domain.Entities.Customer", "Customer")
                    .WithMany("Orders")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("ErpDemo.Domain.Entities.OrderItem", b =>
            {
                b.HasOne("ErpDemo.Domain.Entities.Order", "Order")
                    .WithMany("Items")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Order");
            });

            modelBuilder.Entity("ErpDemo.Domain.Entities.Customer", b =>
            {
                b.Navigation("Orders");
            });

            modelBuilder.Entity("ErpDemo.Domain.Entities.Order", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
